import crypto from "node:crypto";
import { getSupabase } from '../utils/supabase.js';
import { getIO } from '../utils/io.js';
import { uploadEvidenceToCloudinary } from '../middleware/evidenceUpload.js';
import { logAuditEvent } from '../services/auditService.js';
import { emitCommunication, COMMUNICATION_EVENTS } from '../services/communicationEvents.service.js';

const sb=()=>getSupabase();
const actor=req=>req.user?.id;
const role=req=>req.user?.effectiveRole||req.user?.role;
const staff=['admin','superadmin','escrow_officer','executive'];
const involved=(e,id)=>[e.buyer,e.seller].filter(Boolean).map(String).includes(String(id));
const deny=(res)=>res.status(403).json({success:false,message:'Dispute access denied'});
const emit=(e,type)=>{ const io=getIO(); if(!io)return; const payload={disputeId:e.id,escrowId:e.id,type,status:e.disputeWorkflowStatus,at:new Date().toISOString()}; io.to('admins').emit('disputeUpdate',payload); if(e.buyer)io.to(`user_${e.buyer}`).emit('disputeUpdate',payload); if(e.seller)io.to(`user_${e.seller}`).emit('disputeUpdate',payload); if(e.disputeChatId)io.to(`chat_${e.disputeChatId}`).emit('disputeUpdate',payload); };
const getEscrow=async id=>{const {data,error}=await sb().from('escrows').select('*').eq('id',id).single();if(error||!data)return null;return data};

export async function createDispute(req,res){
 const e=await getEscrow(req.body.escrowId); if(!e)return res.status(404).json({success:false,message:'Escrow not found'}); if(!involved(e,actor(req))&&!staff.includes(role(req)))return deny(res);
 const {data,error}=await sb().rpc('kayad_open_dispute_atomic',{p_escrow_id:e.id,p_actor_id:actor(req),p_role:role(req),p_title:req.body.title,p_description:req.body.description,p_category:req.body.category,p_priority:req.body.priority||'medium',p_idempotency_key:req.get('Idempotency-Key')||null});
 if(error)return res.status(400).json({success:false,message:error.message}); const out=data?.escrow||data; emit(out,'opened'); await Promise.all([e.buyer,e.seller].filter(Boolean).map(userId=>emitCommunication({userId,eventType:COMMUNICATION_EVENTS.DISPUTE_OPENED,title:'Dispute opened',message:`A dispute has been opened for escrow ${e.id}.`,channels:['in_app','email','sms','whatsapp'],metadata:{escrowId:e.id,category:req.body.category,priority:req.body.priority||'medium'}}).catch(()=>{}))); await logAuditEvent({action:'dispute_opened',actor:actor(req),target:e.id,targetModel:'Escrow',requestId:req.id}); return res.status(201).json({success:true,dispute:out});
}

export async function getUserDisputes(req,res){const {data,error}=await sb().from('escrows').select('*').eq('status','disputed').or(`buyer.eq.${actor(req)},seller.eq.${actor(req)}`).order('disputedAt',{ascending:false});if(error)throw error;res.json({success:true,disputes:data||[]});}
export async function getAllDisputes(req,res){const {data,error}=await sb().from('escrows').select('*').eq('status','disputed').order('disputedAt',{ascending:false});if(error)throw error;res.json({success:true,disputes:data||[]});}
export async function getDispute(req,res){const e=await getEscrow(req.params.id);if(!e||!e.disputeWorkflowStatus)return res.status(404).json({success:false,message:'Dispute not found'});if(!involved(e,actor(req))&&!staff.includes(role(req)))return deny(res);res.json({success:true,dispute:e});}

export async function transitionDisputeState(req,res){const e=await getEscrow(req.params.id);if(!e||e.status!=='disputed')return res.status(404).json({success:false,message:'Dispute not found'});if(!staff.includes(role(req)))return deny(res);const {data,error}=await sb().rpc('kayad_transition_dispute_atomic',{p_escrow_id:e.id,p_actor_id:actor(req),p_role:role(req),p_next_status:req.body.nextStatus,p_reason:req.body.reason||null});if(error)return res.status(409).json({success:false,message:error.message});emit(data,'transition'); await Promise.all([e.buyer,e.seller].filter(Boolean).map(userId=>emitCommunication({userId,eventType:COMMUNICATION_EVENTS.DISPUTE_UPDATED,title:'Dispute updated',message:`Your dispute has moved to ${req.body.nextStatus}.`,channels:['in_app','email','sms','whatsapp'],metadata:{escrowId:e.id,status:req.body.nextStatus}}).catch(()=>{}))); res.json({success:true,dispute:data});}

export async function uploadEvidence(req,res){const e=await getEscrow(req.params.id);if(!e||e.status!=='disputed')return res.status(404).json({success:false,message:'Active dispute not found'});if(!involved(e,actor(req))&&!staff.includes(role(req)))return deny(res);const uploaded=await uploadEvidenceToCloudinary(req.file,req.body.type||'document');const {data,error}=await sb().rpc('kayad_append_dispute_evidence_atomic',{p_escrow_id:e.id,p_actor_id:actor(req),p_role:role(req),p_item:{type:req.body.type,fileName:req.file.originalname,mimeType:req.file.mimetype,size:req.file.size,url:uploaded.url,publicId:uploaded.public_id,thumbnailUrl:uploaded.thumb,description:req.body.description||''}});if(error)throw error;emit(e,'evidence');res.status(201).json({success:true,...data});}
export async function getEvidence(req,res){const e=await getEscrow(req.params.id);if(!e)return res.status(404).json({success:false,message:'Dispute not found'});if(!involved(e,actor(req))&&!staff.includes(role(req)))return deny(res);res.json({success:true,evidence:e.disputeEvidence||[]});}
export async function getEvidenceItem(req,res){const e=await getEscrow(req.params.id);const item=(e?.disputeEvidence||[]).find(x=>String(x._id)===String(req.params.evidenceId));if(!item)return res.status(404).json({success:false,message:'Evidence not found'});if(!involved(e,actor(req))&&!staff.includes(role(req)))return deny(res);res.json({success:true,evidence:item});}
export async function deleteEvidence(req,res){const e=await getEscrow(req.params.id);if(!e||!staff.includes(role(req)))return deny(res);const arr=(e.disputeEvidence||[]).filter(x=>String(x._id)!==String(req.params.evidenceId));const {data,error}=await sb().from('escrows').update({disputeEvidence:arr,updatedAt:new Date().toISOString()}).eq('id',e.id).select().single();if(error)throw error;emit(data,'evidence');res.json({success:true,dispute:data});}
export async function verifyEvidence(req,res){const e=await getEscrow(req.params.id);if(!e||!staff.includes(role(req)))return deny(res);const arr=(e.disputeEvidence||[]).map(x=>String(x._id)===String(req.params.evidenceId)?{...x,verified:true,verifiedBy:actor(req),verifiedAt:new Date().toISOString()}:x);const {data,error}=await sb().from('escrows').update({disputeEvidence:arr,updatedAt:new Date().toISOString()}).eq('id',e.id).select().single();if(error)throw error;emit(data,'evidence');res.json({success:true,evidence:arr.find(x=>String(x._id)===String(req.params.evidenceId))});}

export async function addInternalNote(req,res){const e=await getEscrow(req.params.id);if(!e||!staff.includes(role(req)))return deny(res);const notes=[...(e.disputeInternalNotes||[]),{id:crypto.randomUUID(),note:req.body.note,isPrivate:req.body.isPrivate!==false,actor:actor(req),createdAt:new Date().toISOString()}];const {data,error}=await sb().from('escrows').update({disputeInternalNotes:notes,updatedAt:new Date().toISOString()}).eq('id',e.id).select().single();if(error)throw error;emit(data,'note');res.json({success:true,notes});}
export async function assignDispute(req,res){const e=await getEscrow(req.params.id);if(!e||!staff.includes(role(req)))return deny(res);const {data,error}=await sb().from('escrows').update({disputeAssignedTo:req.body.assigneeId,updatedAt:new Date().toISOString(),disputeTimeline:[...(e.disputeTimeline||[]),{action:'Assigned',actor:actor(req),assigneeId:req.body.assigneeId,at:new Date().toISOString()}]}).eq('id',e.id).select().single();if(error)throw error;emit(data,'assigned');res.json({success:true,dispute:data});}
export async function startMediation(req,res){const e=await getEscrow(req.params.id);if(!e||!staff.includes(role(req)))return deny(res);const {data,error}=await sb().rpc('kayad_transition_dispute_atomic',{p_escrow_id:e.id,p_actor_id:actor(req),p_role:role(req),p_next_status:'mediation',p_reason:req.body.scheduledAt||'Mediation started'});if(error)throw error;const patch={disputeMediation:{mediatorId:req.body.mediatorId||actor(req),scheduledAt:req.body.scheduledAt||null,startedAt:new Date().toISOString()}};const u=await sb().from('escrows').update(patch).eq('id',e.id).select().single();if(u.error)throw u.error;emit(u.data,'mediation');res.json({success:true,dispute:u.data});}
export async function completeMediation(req,res){const e=await getEscrow(req.params.id);if(!e||!staff.includes(role(req)))return deny(res);const buyerSatisfied=!!req.body.buyerSatisfied;const sellerSatisfied=!!req.body.sellerSatisfied;const patch={disputeMediation:{...(e.disputeMediation||{}),completedAt:new Date().toISOString(),outcome:req.body.outcome,mediatorNotes:req.body.mediatorNotes||'',buyerSatisfied,sellerSatisfied}};const u=await sb().from('escrows').update(patch).eq('id',e.id).select().single();if(u.error)throw u.error;let dispute=u.data;if(buyerSatisfied&&sellerSatisfied){const transition=await sb().rpc('kayad_transition_dispute_atomic',{p_escrow_id:e.id,p_actor_id:actor(req),p_role:role(req),p_next_status:'resolved',p_reason:req.body.outcome||'Mediation successfully completed'});if(transition.error)throw transition.error;dispute=transition.data?.escrow||transition.data;}emit(dispute,'mediation_complete');res.json({success:true,dispute});}
export async function resolveDispute(req,res){const e=await getEscrow(req.params.id);if(!e||!staff.includes(role(req)))return deny(res);const {data,error}=await sb().rpc('kayad_resolve_dispute_atomic',{p_escrow_id:e.id,p_actor_id:actor(req),p_decision:req.body.decision,p_amount:req.body.amount??null,p_seller_amount:req.body.sellerAmount??null,p_buyer_amount:req.body.buyerAmount??null,p_reason:req.body.reason||null,p_idempotency_key:req.get('Idempotency-Key')||null});if(error)return res.status(409).json({success:false,message:error.message});const out=data?.escrow||data;emit(out,'resolved'); await Promise.all([e.buyer,e.seller].filter(Boolean).map(userId=>emitCommunication({userId,eventType:COMMUNICATION_EVENTS.DISPUTE_RESOLVED,title:'Dispute resolved',message:'Your KAYAD dispute has been resolved.',channels:['in_app','email','sms','whatsapp'],metadata:{escrowId:e.id,decision:req.body.decision}}).catch(()=>{})));res.json({success:true,dispute:out});}
export async function submitAppeal(req,res){const e=await getEscrow(req.params.id);if(!e||!involved(e,actor(req)))return deny(res);const {data,error}=await sb().rpc('kayad_transition_dispute_atomic',{p_escrow_id:e.id,p_actor_id:actor(req),p_role:role(req),p_next_status:'appealed',p_reason:req.body.reason});if(error)throw error;const u=await sb().from('escrows').update({disputeAppeal:{reason:req.body.reason,additionalDetails:req.body.additionalDetails||'',submittedBy:actor(req),submittedAt:new Date().toISOString(),status:'pending'}}).eq('id',e.id).select().single();if(u.error)throw u.error;emit(u.data,'appeal');res.json({success:true,dispute:u.data});}
export async function reviewAppeal(req,res){const e=await getEscrow(req.params.id);if(!e||!staff.includes(role(req)))return deny(res);if(!e.disputeAppeal||e.disputeAppeal.status!=='pending')return res.status(409).json({success:false,message:'No pending appeal'});const decision=req.body.decision;const status=decision==='approve'?'under_review':decision==='reject'?'closed':'under_review';const {data,error}=await sb().rpc('kayad_transition_dispute_atomic',{p_escrow_id:e.id,p_actor_id:actor(req),p_role:role(req),p_next_status:status,p_reason:req.body.reviewNotes||decision});if(error)throw error;const u=await sb().from('escrows').update({disputeAppeal:{...e.disputeAppeal,status:decision==='reject'?'rejected':'approved',reviewedBy:actor(req),reviewedAt:new Date().toISOString(),reviewNotes:req.body.reviewNotes||''}}).eq('id',e.id).select().single();if(u.error)throw u.error;emit(u.data,'appeal');res.json({success:true,dispute:u.data});}
export async function getDisputeStats(req,res){const {data,error}=await sb().from('escrows').select('disputeWorkflowStatus,disputeCategory,disputePriority').eq('status','disputed');if(error)throw error;const rows=data||[];const group=k=>rows.reduce((a,x)=>{a[x[k]||'unknown']=(a[x[k]||'unknown']||0)+1;return a},{});res.json({success:true,stats:{total:rows.length,status:group('disputeWorkflowStatus'),category:group('disputeCategory'),priority:group('disputePriority')}});}
