apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kayad-uploads-pvc
  namespace: kayad
  labels:
    app: kayad-backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
