from pathlib import Path
p=Path('/mnt/data/phase16')
f=p/'src/features/FinancingView.tsx'; s=f.read_text()
s=s.replace("import React, { useState, useMemo, useRef } from 'react';", "import React, { useState, useMemo, useRef, useEffect } from 'react';")
s=s.replace("import { PageHeader, StatWidget, Card, Badge, Button, LazyImage } from '../components/ui';", "import { PageHeader, StatWidget, Card, Badge, Button, LazyImage } from '../components/ui';\nimport { useAuth } from '../context/AuthContext';\nimport { createLoanApplication, getMyLoanApplications, LoanApiError, type LoanApplication } from '../services/loanApi';")
s=s.replace("  // Mode Switcher: 'buyer' | 'bank_portal'", "  const { user } = useAuth();\n\n  // Mode Switcher: 'buyer' | 'bank_portal'")
a=s.index('  // Application Form State'); b=s.index('  // FAQ Accordion State',a)
state='''  // Application Form State\n  const [activeTab, setActiveTab] = useState<'calculator' | 'lenders' | 'comparison' | 'tracker' | 'eligibility'>('calculator');\n  const [selectedBankForApply, setSelectedBankForApply] = useState<PartnerBank | null>(null);\n  const [isApplyModalOpen, setIsApplyModalOpen] = useState<boolean>(false);\n  const [applicationSuccess, setApplicationSuccess] = useState<boolean>(false);\n  const [applicationSubmitting, setApplicationSubmitting] = useState(false);\n  const [applicationError, setApplicationError] = useState<string | null>(null);\n  const [monthlyIncome, setMonthlyIncome] = useState<number>(0);\n  const [currentApplication, setCurrentApplication] = useState<LoanApplication | null>(null);\n  const currentAppStatus: ApplicationStatus | null = currentApplication\n    ? ({ submitted: 'Submitted', under_review: 'Under Review', approved: 'Approved', declined: 'Declined', withdrawn: 'Declined' } as const)[currentApplication.status]\n    : null;\n  const uploadedDocs: Record<string, boolean> = {};\n\n  useEffect(() => {\n    if (!user) { setCurrentApplication(null); return; }\n    let cancelled = false;\n    getMyLoanApplications().then(apps => {\n      if (!cancelled) setCurrentApplication(apps[0] || null);\n    }).catch(() => {\n      if (!cancelled) setCurrentApplication(null);\n    });\n    return () => { cancelled = true; };\n  }, [user]);\n\n'''
s=s[:a]+state+s[b:]
a=s.index('  // Partner Banks Dataset'); b=s.index('  // Filtered compare list',a)
s=s[:a]+'''  // Lender offers must come from a verified backend partner directory.\n  // Until that contract is connected, do not present invented rates, fees,\n  // eligibility thresholds, approval times, or partner names as live offers.\n  const partnerBanks: PartnerBank[] = useMemo(() => [], []);\n\n'''+s[b:]
a=s.index('  const handleOpenApply'); b=s.index('  // Only real marketplace vehicles',a)
s=s[:a]+'''  const handleOpenApply = () => {\n    setSelectedBankForApply({\n      id: 'kayad-financing', name: 'KAYAD Financing Request', shortName: 'KAYAD',\n      logoBg: 'bg-[#1E3063] text-white', rateRange: 'Not quoted', baseRate: annualInterestRate,\n      maxFinancing: 'Subject to lender terms', minDepositPercent: depositPercent, maxTermMonths: tenureMonths,\n      approvalTime: 'Not quoted', earlyRepaymentPolicy: 'Subject to lender terms',\n      eligibilitySummary: 'Submitting this request does not imply lender approval or a lender offer.', badge: 'Request', features: []\n    });\n    setIsApplyModalOpen(true); setApplicationSuccess(false); setApplicationError(null);\n  };\n\n  const submitFinancingRequest = async (e: React.FormEvent) => {\n    e.preventDefault();\n    if (!user) { setApplicationError('Please sign in before submitting a financing request.'); return; }\n    setApplicationSubmitting(true); setApplicationError(null);\n    try {\n      const created = await createLoanApplication({ vehiclePrice, depositAmount, loanAmount, termMonths: tenureMonths, monthlyIncome: monthlyIncome || undefined, employmentStatus: employmentType });\n      setCurrentApplication(created); setApplicationSuccess(true);\n    } catch (err) {\n      setApplicationError(err instanceof LoanApiError ? err.message : 'Could not submit the financing request.');\n    } finally { setApplicationSubmitting(false); }\n  };\n\n  const handleDocToggle = () => {\n    setApplicationError('Document upload is not connected yet. No document was marked as verified.');\n  };\n\n'''+s[b:]
# calculator CTA
s=s.replace("onClick={() => {\n                setActiveTab('lenders');\n              }}", "onClick={handleOpenApply}",1)
s=s.replace('<span>Compare Lenders for this Plan</span>','<span>Submit Financing Request</span>')
# lender cards through comparison marker
needle='        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">'
if needle in s:
 a=s.index(needle); b=s.index('      {/* ==========================================\n          5. COMPARE FINANCING OFFERS',a)
 s=s[:a]+'''        <Card className="p-6 bg-slate-50 border-slate-200">\n          <div className="flex items-start gap-3"><Info className="w-5 h-5 text-amber-600 shrink-0" /><div><p className="font-extrabold text-[#1E3063]">Verified lender offers are not connected yet</p><p className="text-sm text-slate-600 mt-1">KAYAD will not display invented lender rates, fees, approval times, or eligibility claims. Submit a real financing request instead.</p></div></div>\n        </Card>\n      </div>\n\n'''+s[b:]
# comparison section through journey marker
st=s.index('      {/* ==========================================\n          5. COMPARE FINANCING OFFERS')
en=s.index('      {/* ==========================================\n          6. APPLICATION JOURNEY & STATUS TRACKER',st)
s=s[:st]+'''      {/* ==========================================\n          5. COMPARE FINANCING OFFERS\n          ========================================== */}\n      {activeTab === 'comparison' && <Card className="p-6 bg-slate-50 border-slate-200"><div className="flex items-start gap-3"><Info className="w-5 h-5 text-amber-600" /><div><h2 className="text-xl font-black text-[#1E3063]">Lender comparison unavailable</h2><p className="text-sm text-slate-600 mt-1">A verified lender-offer feed is not connected yet. No synthetic comparison data is shown.</p></div></div></Card>}\n\n'''+s[en:]
# status card: replace entire tracker body after journey header with honest real application card, before doc module
st=s.index('      {/* ==========================================\n          6. APPLICATION JOURNEY & STATUS TRACKER')
en=s.index('      {/* ==========================================\n          7. SECURE DOCUMENT UPLOAD MODULE',st)
tracker='''      {/* ==========================================\n          6. APPLICATION JOURNEY & STATUS TRACKER\n          ========================================== */}\n      <div className="space-y-6 pt-4">\n        <div className="flex items-center justify-between flex-wrap gap-2">\n          <div><h2 className="text-xl font-black text-[#1E3063] font-display flex items-center gap-2"><Clock className="w-5 h-5 text-amber-500" />Application Journey & Live Tracker</h2><p className="text-xs text-slate-500 font-medium">Status is read from your real backend loan application.</p></div>\n          <div className="text-[11px] text-slate-500 font-semibold px-2 py-1.5 rounded-lg bg-slate-50 border border-slate-200">Backend-authoritative</div>\n        </div>\n        {currentApplication ? (\n          <Card className="p-6 bg-slate-50 border-slate-200 space-y-4">\n            <div className="flex items-center justify-between border-b border-slate-200 pb-3 flex-wrap gap-2"><div><p className="text-[10px] text-slate-400 font-extrabold uppercase tracking-wider">Application {currentApplication.id}</p><h3 className="text-base font-extrabold text-[#1E3063]">Vehicle Financing Request</h3></div><Badge variant={currentAppStatus === 'Approved' ? 'success' : currentAppStatus === 'Declined' ? 'danger' : 'escrow'} size="md">Current Status: {currentAppStatus}</Badge></div>\n            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs"><div className="bg-white p-4 rounded-xl border border-slate-200"><p className="text-slate-400">Vehicle Asset Value</p><p className="font-extrabold text-[#1E3063]">Ksh {Number(currentApplication.vehiclePrice || 0).toLocaleString()}</p></div><div className="bg-white p-4 rounded-xl border border-slate-200"><p className="text-slate-400">Requested Loan</p><p className="font-extrabold text-emerald-700">Ksh {Number(currentApplication.loanAmount || 0).toLocaleString()}</p></div><div className="bg-white p-4 rounded-xl border border-slate-200"><p className="text-slate-400">Submitted</p><p className="font-extrabold text-[#1E3063]">{new Date(currentApplication.createdAt).toLocaleString('en-KE')}</p></div></div>\n            <p className="text-xs text-slate-500">KAYAD does not fabricate lender-side approvals, document verification, disbursement, or callback promises.</p>\n          </Card>\n        ) : (\n          <Card className="p-6 bg-slate-50 border-slate-200"><p className="text-sm text-slate-600">No financing application has been submitted from this account yet.</p></Card>\n        )}\n      </div>\n\n'''
s=s[:st]+tracker+s[en:]
# modal copy/form
s=s.replace('Direct Lender Pre-Qualification Route','KAYAD Financing Request')
s=s.replace('Apply for Pre-Approval with {selectedBankForApply.name}','Submit a Financing Request')
s=s.replace('Fast-track lead submission to {selectedBankForApply.shortName} asset financing desk.','This submits a real financing application to the KAYAD backend. It does not imply lender approval or a lender offer.')
s=s.replace('Pre-Approval Lead Submitted!','Financing Request Submitted')
s=s.replace('Your pre-qualification file has been securely routed to <strong>{selectedBankForApply.shortName}</strong>. A dedicated bank asset officer will call you within 2 business hours.','Your financing request was recorded by the KAYAD backend. No lender approval or callback time is promised.')
s=s.replace('''onSubmit={(e) => {\n                  e.preventDefault();\n                  setApplicationSuccess(true);\n                  setCurrentAppStatus('Submitted');\n                }}''','onSubmit={submitFinancingRequest}')
# remove fake identity block by exact range between form inputs and monthly income
start=s.index('                {/* Form Inputs */}')
mi=s.index('                  <div>\n                    <label className="font-bold text-slate-700">Monthly Gross Income (Ksh)</label>',start)
end=s.index('                </div>\n\n                <div className="pt-2">',mi)
mi_block=s[mi:end] 
mi_block=mi_block.replace('''placeholder="e.g. 120000"''','''placeholder="e.g. 120000"\n                      value={monthlyIncome || ''}\n                      onChange={(e) => setMonthlyIncome(Number(e.target.value) || 0)}''')
s=s[:start]+'''                {/* Form Inputs — only fields supported by the real loan API */}\n                <div className="space-y-3">\n'''+mi_block+'''                </div>\n\n'''+s[end+len('                </div>\n\n'):]
s=s.replace('<span>Submit Pre-Approval Lead to {selectedBankForApply.shortName}</span>','<span>{applicationSubmitting ? \'Submitting…\' : \'Submit Financing Request\'}</span>')
s=s.replace('''                    type="submit"\n                  >''','''                    type="submit"\n                    disabled={applicationSubmitting}\n                  >''',1)
s=s.replace('''                <div className="pt-2">''','''                {applicationError && <div className="p-3 rounded-xl border border-rose-200 bg-rose-50 text-rose-700">{applicationError}</div>}\n                <div className="pt-2">''',1)
f.write_text(s)

# admin sample rules
f=p/'src/pages/admin/automation/components/BusinessRulesManager.jsx'; s=f.read_text()
a=s.index('// Sample rules'); b=s.index('const statusColors',a)
s=s[:a]+'''// Rules are backend-authoritative. Never seed fabricated rules, execution counts, or timestamps.\nconst initialRules = [];\n\n'''+s[b:]
s=s.replace('useState(sampleRules)','useState(initialRules)')
a=s.index('  const saveRule = () => {'); b=s.index('  return (',a)
s=s[:a]+'''  const saveRule = () => {\n    console.warn('[BusinessRulesManager] Backend CRUD integration is not connected; rule was not persisted.');\n  };\n\n  const toggleRuleStatus = () => {\n    console.warn('[BusinessRulesManager] Backend CRUD integration is not connected; status was not changed.');\n  };\n\n'''+s[b:]
f.write_text(s)
