import { Router } from "express";
import { authLimiter } from "../middleware/rateLimiter.ts";

import authRoutes from "./authRoutes.ts";
import carRoutes from "./carRoutes.ts";
import bidRoutes from "./bidRoutes.ts";
import dealerRoutes from "./dealerRoutes.ts";
import adminRoutes from "./adminRoutes.ts";
import paymentRoutes from "./paymentRoutes.ts";
import escrowRoutes from "./escrowRoutes.ts";
import chatRoutes from "./chatRoutes.ts";
import favoriteRoutes from "./favoriteRoutes.ts";
import notificationRoutes from "./notificationRoutes.ts";
import reviewRoutes from "./reviewRoutes.ts";
import transactionRoutes from "./transactionRoutes.ts";
import auctionAdminRoutes from "./auctionAdminRoutes.ts";
import adRoutes from "./adRoutes.ts";
import userRoutes from "./userRoutes.ts";
import savedSearchRoutes from "./savedSearchRoutes.ts";
import ntsaVerificationRoutes from "./ntsaVerificationRoutes.ts";
import inspectionRoutes from "./inspectionRoutes.ts";
import escrowVaultRoutes from "./escrowVaultRoutes.ts";
import securityLogRoutes from "./securityLogRoutes.ts";
import smsBiddingRoutes from "./smsBiddingRoutes.ts";
import inspectorApplicationRoutes from "./inspectorApplicationRoutes.ts";
import referralRoutes from "./referralRoutes.ts";
import contactRoutes from "./contactRoutes.ts";
import marketRoutes from "./marketRoutes.ts";

const router = Router();

router.use("/auth", authLimiter, authRoutes);
router.use("/cars", carRoutes);
router.use("/bids", bidRoutes);
router.use("/dealer", dealerRoutes);
router.use("/admin", adminRoutes);
router.use("/payments", paymentRoutes);
router.use("/escrow", escrowRoutes);
router.use("/chat", chatRoutes);
router.use("/favorites", favoriteRoutes);
router.use("/notifications", notificationRoutes);
router.use("/reviews", reviewRoutes);
router.use("/transactions", transactionRoutes);
router.use("/auction-admin", auctionAdminRoutes);
router.use("/ads", adRoutes);
router.use("/users", userRoutes);
router.use("/saved-searches", savedSearchRoutes);
router.use("/ntsa-verification", ntsaVerificationRoutes);
router.use("/inspections", inspectionRoutes);
router.use("/escrow-vault", escrowVaultRoutes);
router.use("/security-logs", securityLogRoutes);
router.use("/sms-bidding", smsBiddingRoutes);
router.use("/inspector-applications", inspectorApplicationRoutes);
router.use("/referral", referralRoutes);
router.use("/contact", contactRoutes);
router.use("/market", marketRoutes);

export default router;
