// jest.config.js
export default {
  testEnvironment: "node",
  preset: null,
  transform: {},
  testMatch: ["**/tests/**/*.test.js"],
  testTimeout: 60000,
  forceExit: true,
  detectOpenHandles: true,
  verbose: false,
  maxWorkers: 1,
  modulePathIgnorePatterns: ["node_modules"],
  collectCoverage: true,
  collectCoverageFrom: [
    "utils/**/*.js",
    "middleware/**/*.js",
    "services/**/*.js",
    "controllers/**/*.js",
    "models/**/*.js",
    "!**/node_modules/**",
    "!**/tests/**",
    "!**/migrations/**",
    "!**/seed.js",
    "!**/server.js",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html", "json-summary"],
  coverageThreshold: {
    global: {
      branches: 50,
      functions: 50,
      lines: 50,
      statements: 50,
    },
    "./controllers/": {
      branches: 60,
      functions: 60,
      lines: 60,
      statements: 60,
    },
    "./services/": {
      branches: 60,
      functions: 60,
      lines: 60,
      statements: 60,
    },
    "./middleware/": {
      branches: 50,
      functions: 50,
      lines: 50,
      statements: 50,
    },
  },
};
