// jest.config.js
export default {
  testEnvironment: "node",
  transform: {},
  testMatch: ["**/tests/**/*.test.js"],
  testTimeout: 60000,
  forceExit: true,
  detectOpenHandles: true,
  verbose: false,
  maxWorkers: 1,
  collectCoverage: true,
  collectCoverageFrom: [
    "utils/**/*.js",
    "middleware/**/*.js",
    "services/**/*.js",
    "controllers/**/*.js",
    "models/**/*.js",
    "!**/node_modules/**",
    "!**/tests/**",
    "!**/migrations/**",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "clover", "html"],
  coverageThresholds: {
    global: {
      branches: 75,
      functions: 75,
      lines: 75,
      statements: 75,
    },
    "./controllers/": {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
    "./services/": {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
    "./middleware/": {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
};
