// jest.config.js
export default {
  testEnvironment: "node",
  preset: null,
  transform: {},
  testMatch: ["**/tests/**/*.test.js"],
  testTimeout: 60000,
  forceExit: true,
  detectOpenHandles: true,
  verbose: false,
  maxWorkers: 1,
  modulePathIgnorePatterns: ["node_modules"],
  collectCoverage: true,
  collectCoverageFrom: [
    "utils/**/*.js",
    "middleware/**/*.js",
    "services/**/*.js",
    "controllers/**/*.js",
    "models/**/*.js",
    "!**/node_modules/**",
    "!**/tests/**",
    "!**/migrations/**",
    "!**/seed.js",
    "!**/server.js",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html", "json-summary"],
  coverageThreshold: {
    global: {
      branches: 5,
      functions: 10,
      lines: 8,
      statements: 8,
    },
    "./controllers/": {
      branches: 0,
      functions: 0,
      lines: 0,
      statements: 0,
    },
    "./services/": {
      branches: 0,
      functions: 0,
      lines: 0,
      statements: 0,
    },
    "./middleware/": {
      branches: 0,
      functions: 0,
      lines: 0,
      statements: 0,
    },
  },
};
