/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GhostCheckRouteImport } from './routes/ghost-check'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DealerApplicationRouteImport } from './routes/dealer-application'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostCheckRoute = GhostCheckRouteImport.update({
  id: '/ghost-check',
  path: '/ghost-check',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerApplicationRoute = DealerApplicationRouteImport.update({
  id: '/dealer-application',
  path: '/dealer-application',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dealer-application': typeof DealerApplicationRoute
  '/gallery': typeof GalleryRoute
  '/ghost-check': typeof GhostCheckRoute
  '/how-it-works': typeof HowItWorksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dealer-application': typeof DealerApplicationRoute
  '/gallery': typeof GalleryRoute
  '/ghost-check': typeof GhostCheckRoute
  '/how-it-works': typeof HowItWorksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dealer-application': typeof DealerApplicationRoute
  '/gallery': typeof GalleryRoute
  '/ghost-check': typeof GhostCheckRoute
  '/how-it-works': typeof HowItWorksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auctions'
    | '/auth'
    | '/dashboard'
    | '/dealer-application'
    | '/gallery'
    | '/ghost-check'
    | '/how-it-works'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auctions'
    | '/auth'
    | '/dashboard'
    | '/dealer-application'
    | '/gallery'
    | '/ghost-check'
    | '/how-it-works'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auctions'
    | '/auth'
    | '/dashboard'
    | '/dealer-application'
    | '/gallery'
    | '/ghost-check'
    | '/how-it-works'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuctionsRoute: typeof AuctionsRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DealerApplicationRoute: typeof DealerApplicationRoute
  GalleryRoute: typeof GalleryRoute
  GhostCheckRoute: typeof GhostCheckRoute
  HowItWorksRoute: typeof HowItWorksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghost-check': {
      id: '/ghost-check'
      path: '/ghost-check'
      fullPath: '/ghost-check'
      preLoaderRoute: typeof GhostCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer-application': {
      id: '/dealer-application'
      path: '/dealer-application'
      fullPath: '/dealer-application'
      preLoaderRoute: typeof DealerApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuctionsRoute: AuctionsRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DealerApplicationRoute: DealerApplicationRoute,
  GalleryRoute: GalleryRoute,
  GhostCheckRoute: GhostCheckRoute,
  HowItWorksRoute: HowItWorksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
