import fs from 'node:fs';
const read = (file) => fs.readFileSync(file, 'utf8');
const checks = [];
const pass = (name, ok) => { checks.push({ name, ok }); console.log(`${ok ? 'PASS' : 'FAIL'}: ${name}`); };
const controller = read('backend/controllers/paymentController.js');
const api = read('src/api/api.exports.ts');
const app = read('src/App.tsx');
const navbar = read('src/components/Navbar.tsx');
const view = read('src/features/PaymentHistoryView.tsx');
pass('Payment history uses canonical Payment model', controller.includes('import Payment from "../models/Payment.js";') && controller.includes('Payment.find(filters)'));
pass('User payment query is scoped to authenticated user', controller.includes('const filters = { user: req.user.id };'));
pass('Payment query uses real payment fields', controller.includes('mpesaReceipt checkoutRequestId') && controller.includes('referenceId referenceModel mode processed paidAt metadata'));
pass('Payment history supports server-side status filters', controller.includes('VALID_STATUSES') && controller.includes('filters.status = req.query.status'));
pass('Payment history supports pagination and total count', controller.includes('Payment.countDocuments(filters)') && controller.includes('pagination: { page, limit, total, pages: Math.ceil(total / limit) }'));
pass('Frontend payment API accepts query params', api.includes("myPayments:  (params?: any) => api.get('/payments/my', { params }).then(unwrap)"));
pass('Live payment history view exists', fs.existsSync('src/features/PaymentHistoryView.tsx'));
pass('Payment history consumes real payments API', view.includes('paymentsAPI.myPayments') && view.includes('paymentsAPI.status'));
pass('Payment history is wired into the authenticated app', app.includes("activeNav === 'payments' && user && <PaymentHistoryView />"));
pass('Payment history is reachable from authenticated navigation', navbar.includes("handleNavSelect('payments')") && navbar.includes('Payment History'));
pass('No fabricated payment history data introduced', !view.includes('MOCK_') && !view.includes('localStorage') && !view.includes('walletBalance'));
const failed = checks.filter((c) => !c.ok).length;
console.log(`\nPhase 54 validation: ${checks.length - failed}/${checks.length} passed`);
if (failed) process.exit(1);
