import fs from 'node:fs';
const read = (file) => fs.readFileSync(file, 'utf8');
const checks = [];
const pass = (name, ok) => { checks.push({ name, ok }); console.log(`${ok ? 'PASS' : 'FAIL'}: ${name}`); };
const marketplace = read('src/context/MarketplaceContext.tsx');
const notification = read('src/context/NotificationContext.tsx');
const panel = read('src/components/layout/NotificationPanel.tsx');
const app = read('src/App.tsx');
pass('MarketplaceContext no longer owns notification state', !marketplace.includes('const [notifications, setNotifications]'));
pass('MarketplaceContext no longer exposes local notification methods', !marketplace.includes('markNotificationRead') && !marketplace.includes('unreadNotifsCount'));
pass('bid flow no longer fabricates local notification records', !marketplace.includes('Bid Placed Successfully'));
pass('escrow flow no longer fabricates local notification records', !marketplace.includes('Escrow Initiated'));
pass('price alert flow no longer fabricates local notification records', !marketplace.includes('Price Alert Set'));
pass('NotificationContext owns authoritative notification records', notification.includes('notifAPI.list') && notification.includes('setNotifications(list)'));
pass('NotificationPanel consumes NotificationContext', panel.includes('useNotifications') && !panel.includes('useMarketplace'));
pass('NotificationPanel uses backend notification read action', panel.includes('markAsRead(notif._id)'));
pass('App mounts SocketProvider and NotificationProvider under AuthProvider', app.includes('<SocketProvider>') && app.includes('<NotificationProvider>') && app.includes('<AuthProvider>'));
pass('App preserves consolidated CompareProvider', app.includes('<CompareProvider>'));
pass('App ref regression remains absent', app.includes('React.useRef(new Set<string>())') && !app.includes('React.useRef<Set<string>>(new Set())'));
const failed = checks.filter(c => !c.ok).length;
console.log(`\nPhase 50 validation: ${checks.length - failed}/${checks.length} passed`);
if (failed) process.exit(1);
