-- P0-A operational schema reconciliation
-- Applied to production project ubvgixwhfybbyjuvxboj on 2026-09-19.
-- Service-role-only tables; no anon/authenticated table privileges.

create table if not exists public.transactions (id uuid primary key default gen_random_uuid(), user_id uuid, car_id uuid, payment_id uuid, escrow_id uuid, type text, status text, amount numeric(18,2), currency text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.marketplace_health (id uuid primary key default gen_random_uuid(), timestamp timestamptz not null default now(), active_dealers integer not null default 0, active_buyers integer not null default 0, new_dealers integer not null default 0, new_buyers integer not null default 0, vehicles_listed integer not null default 0, vehicles_sold integer not null default 0, new_listings integer not null default 0, escrow_conversion_rate numeric(12,4), auction_conversion_rate numeric(12,4), lead_conversion_rate numeric(12,4), overall_conversion_rate numeric(12,4), fraud_incidents integer not null default 0, fraud_rate numeric(12,4), disputes integer not null default 0, dispute_rate numeric(12,4), revenue numeric(18,2) not null default 0, payment_success_rate numeric(12,4), payment_failures integer not null default 0, health_score numeric(12,4), health_score_breakdown jsonb not null default '{}'::jsonb, alerts jsonb not null default '[]'::jsonb, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.conversion_funnels (id uuid primary key default gen_random_uuid(), car_id uuid, user_id uuid, dealer_id uuid, current_stage text not null default 'viewed', view_count integer not null default 0, favorited boolean not null default false, favorited_at timestamptz, chatted boolean not null default false, chat_initiated_at timestamptz, message_count integer not null default 0, offer_made boolean not null default false, offer_made_at timestamptz, offer_amount numeric(18,2), escrow_initiated boolean not null default false, escrow_initiated_at timestamptz, sold boolean not null default false, sold_at timestamptz, sale_amount numeric(18,2), last_viewed_at timestamptz, time_to_favorite numeric(12,4), time_to_chat numeric(12,4), time_to_offer numeric(12,4), time_to_escrow numeric(12,4), time_to_sale numeric(12,4), metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.escrow_anomalies (id uuid primary key default gen_random_uuid(), escrow_id uuid, target_user uuid, type text, severity text, status text, description text, detected_at timestamptz not null default now(), resolved_at timestamptz, resolved_by uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.escrow_risk_scores (id uuid primary key default gen_random_uuid(), user_id uuid, role text, risk_score numeric(12,4), risk_tier text, factors jsonb not null default '{}'::jsonb, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.escrow_audits (id uuid primary key default gen_random_uuid(), idempotency_key text, escrow_id uuid, action text, performed_by uuid, timestamp timestamptz not null default now(), details jsonb not null default '{}'::jsonb, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.auction_integrity_flags (id uuid primary key default gen_random_uuid(), target_user uuid, auction uuid, related_auctions uuid[] not null default '{}', category text, severity text, status text, action_taken text, action_notes text, review_notes text, reviewed_by uuid, reviewed_at timestamptz, action_taken_by uuid, action_taken_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.auction_risk_profiles (id uuid primary key default gen_random_uuid(), user_id uuid, role text, risk_score numeric(12,4), risk_tier text, factors jsonb not null default '{}', metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.contacts (id uuid primary key default gen_random_uuid(), name text not null, email text, subject text, message text, read boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ntsa_verification_requests (id uuid primary key default gen_random_uuid(), car uuid, requested_by uuid, status text not null default 'pending', duty_status text, chassis_verified boolean, logbook_verified boolean, import_verified boolean, admin_notes text, reviewed_by uuid, reviewed_at timestamptz, documents jsonb not null default '[]', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.inspector_applications (id uuid primary key default gen_random_uuid(), user_id uuid, full_name text not null, email text not null, phone text, id_number text, location text, years_of_experience integer, specialties text[] not null default '{}', certifications text[] not null default '{}', tools_available text, preferred_regions text[] not null default '{}', cv_url text, certification_docs jsonb not null default '[]', status text not null default 'pending', reviewed_by uuid, reviewed_at timestamptz, review_notes text, assigned_specialty text, assigned_region text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.idempotency_audit_logs (id uuid primary key default gen_random_uuid(), key text, operation_type text, status text, checkout_request_id text, ip text, duration_ms integer, error_message text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.job_failures (id uuid primary key default gen_random_uuid(), job_id text, job_name text, queue_name text, error text, error_message text, error_stack text, error_type text, attempts_made integer, max_attempts integer, retry_count integer, failed_at timestamptz, processing_time integer, job_data jsonb, metadata jsonb not null default '{}', failed_reason text, timestamp timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.bid_logs (id uuid primary key default gen_random_uuid(), bid uuid, car uuid, user_id uuid, auction uuid, bidder_pseudonym text, amount numeric(18,2), previous_amount numeric(18,2), increment numeric(18,2), status text, is_auto_bid boolean not null default false, is_proxy_bid boolean not null default false, source text, ip_address text, user_agent text, location text, display_order bigint, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.sms_bidders (id uuid primary key default gen_random_uuid(), user_id uuid, phone text not null, active boolean not null default true, subscriptions jsonb not null default '[]', last_bid_at timestamptz, total_sms_bids integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.dealer_health_scores (id uuid primary key default gen_random_uuid(), dealer_id uuid, score numeric(12,4), category text, factors jsonb not null default '{}', calculated_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.dealer_analytics (id uuid primary key default gen_random_uuid(), dealer_id uuid, metric text, value numeric(18,4), period_start timestamptz, period_end timestamptz, metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.notification_audit (id uuid primary key default gen_random_uuid(), notification_id uuid, user_id uuid, channel text, event_type text, recipient text, status text, attempts integer not null default 0, error_message text, delivered_at timestamptz, metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());

alter table public.transactions enable row level security;
alter table public.marketplace_health enable row level security;
alter table public.conversion_funnels enable row level security;
alter table public.escrow_anomalies enable row level security;
alter table public.escrow_risk_scores enable row level security;
alter table public.escrow_audits enable row level security;
alter table public.auction_integrity_flags enable row level security;
alter table public.auction_risk_profiles enable row level security;
alter table public.contacts enable row level security;
alter table public.ntsa_verification_requests enable row level security;
alter table public.inspector_applications enable row level security;
alter table public.idempotency_audit_logs enable row level security;
alter table public.job_failures enable row level security;
alter table public.bid_logs enable row level security;
alter table public.sms_bidders enable row level security;
alter table public.dealer_health_scores enable row level security;
alter table public.dealer_analytics enable row level security;
alter table public.notification_audit enable row level security;
revoke all on table public.transactions, public.marketplace_health, public.conversion_funnels, public.escrow_anomalies, public.escrow_risk_scores, public.escrow_audits, public.auction_integrity_flags, public.auction_risk_profiles, public.contacts, public.ntsa_verification_requests, public.inspector_applications, public.idempotency_audit_logs, public.job_failures, public.bid_logs, public.sms_bidders, public.dealer_health_scores, public.dealer_analytics, public.notification_audit from anon, authenticated;
grant all on table public.transactions, public.marketplace_health, public.conversion_funnels, public.escrow_anomalies, public.escrow_risk_scores, public.escrow_audits, public.auction_integrity_flags, public.auction_risk_profiles, public.contacts, public.ntsa_verification_requests, public.inspector_applications, public.idempotency_audit_logs, public.job_failures, public.bid_logs, public.sms_bidders, public.dealer_health_scores, public.dealer_analytics, public.notification_audit to service_role;
