-- Phase 22 canonical reconciliation. Idempotent against the live Phase 22 schema.
-- Apply after the existing KAYAD inspection/dispute/finance migrations.

create table if not exists public.service_jobs (
 id uuid primary key default gen_random_uuid(), provider_id uuid not null references public.inspection_providers(id), requester_id uuid not null references public.users(id),
 car_id uuid references public.cars(id), offering_id uuid references public.vehicle_service_offerings(id), roadside_request_id uuid references public.roadside_service_requests(id),
 status text not null default 'requested' check(status in ('requested','quoted','accepted','scheduled','in_progress','completed','cancelled','disputed','refunded')),
 quoted_amount numeric check(quoted_amount is null or quoted_amount>=0), final_amount numeric check(final_amount is null or final_amount>=0), currency text not null default 'KES',
 scheduled_at timestamptz,accepted_at timestamptz,started_at timestamptz,completed_at timestamptz,cancelled_at timestamptz,cancellation_reason text,idempotency_key text not null,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(provider_id,idempotency_key));
create table if not exists public.service_job_events (
 id uuid primary key default gen_random_uuid(),job_id uuid not null references public.service_jobs(id) on delete cascade,event_type text not null,actor_id uuid references public.users(id),payload jsonb not null default '{}',created_at timestamptz not null default now());
create table if not exists public.service_job_disputes (
 id uuid primary key default gen_random_uuid(),job_id uuid not null references public.service_jobs(id) on delete cascade,raised_by uuid not null references public.users(id),against_provider_id uuid not null references public.inspection_providers(id),dispute_type text not null,description text not null,
 status text not null default 'open' check(status in ('open','investigating','pending_review','resolved','dismissed')),resolution text,resolved_by uuid references public.users(id),resolved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.service_job_dispute_evidence (
 id uuid primary key default gen_random_uuid(),dispute_id uuid not null references public.service_job_disputes(id) on delete cascade,submitted_by uuid not null references public.users(id),evidence_type text not null,evidence jsonb not null default '{}',created_at timestamptz not null default now());
create table if not exists public.inspection_dispute_evidence (
 id uuid primary key default gen_random_uuid(),dispute_id uuid not null references public.inspection_disputes(id) on delete cascade,submitted_by uuid references public.users(id),evidence_type text not null,evidence jsonb not null default '{}',created_at timestamptz not null default now());
create table if not exists public.inspection_risk_flags (
 id uuid primary key default gen_random_uuid(),provider_id uuid references public.inspection_providers(id),user_id uuid references public.users(id),report_id uuid references public.inspection_reports(id),booking_id uuid references public.inspection_bookings(id),flag_type text not null,
 severity text not null default 'medium' check(severity in ('low','medium','high','critical')),status text not null default 'open' check(status in ('open','reviewing','resolved','dismissed')),reason text not null,evidence jsonb not null default '{}',created_at timestamptz not null default now(),resolved_at timestamptz,resolved_by uuid references public.users(id));

alter table public.service_jobs enable row level security; alter table public.service_job_events enable row level security; alter table public.service_job_disputes enable row level security; alter table public.service_job_dispute_evidence enable row level security; alter table public.inspection_dispute_evidence enable row level security; alter table public.inspection_risk_flags enable row level security;
revoke all on public.service_jobs,public.service_job_events,public.service_job_disputes,public.service_job_dispute_evidence,public.inspection_dispute_evidence,public.inspection_risk_flags from public,anon,authenticated;
grant select on public.service_jobs,public.service_job_events,public.service_job_disputes,public.service_job_dispute_evidence,public.inspection_dispute_evidence,public.inspection_risk_flags to service_role;

do $$ begin alter table public.inspection_reviews add constraint inspection_reviews_rating_ck check(rating between 1 and 5); exception when duplicate_object then null; end $$;
do $$ begin alter table public.inspection_reviews add constraint inspection_reviews_booking_reviewer_uq unique(booking_id,reviewer_id); exception when duplicate_object then null; end $$;

create or replace function public.kayad_inspection_report_immutability_guard() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin if old.is_locked and (new.booking_id<>old.booking_id or new.report_number<>old.report_number or new.overall_score is distinct from old.overall_score or new.overall_condition is distinct from old.overall_condition or new.findings is distinct from old.findings or new.critical_issues is distinct from old.critical_issues or new.recommendations is distinct from old.recommendations or new.executive_summary is distinct from old.executive_summary or new.detailed_findings is distinct from old.detailed_findings or new.technician_notes is distinct from old.technician_notes or new.diagnostic_codes is distinct from old.diagnostic_codes or new.photos is distinct from old.photos or new.quality_score is distinct from old.quality_score or new.pdf_url is distinct from old.pdf_url or new.version is distinct from old.version) then raise exception 'Locked inspection evidence is immutable; create a new report version instead'; end if; return new; end; $$;
drop trigger if exists trg_inspection_report_immutability on public.inspection_reports;
create trigger trg_inspection_report_immutability before update on public.inspection_reports for each row execute function public.kayad_inspection_report_immutability_guard();

-- Provider registration ambiguity fix.
create or replace function public.kayad_create_inspection_provider_application(p_user_id uuid,p_profile jsonb) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare u public.users%rowtype; provider_id uuid;
begin select usr.* into u from public.users usr where usr.id=p_user_id for update; if not found or u.status<>'approved' or coalesce(u.is_banned,false) then raise exception 'User is not eligible to register as an inspection partner'; end if;
select ip.id into provider_id from public.inspection_providers ip where ip.user_id=p_user_id order by ip.created_at desc limit 1;
if provider_id is not null then update public.inspection_providers set company_name=coalesce(nullif(p_profile->>'companyName',''),company_name),trading_name=coalesce(nullif(p_profile->>'tradingName',''),trading_name),business_type=coalesce(nullif(p_profile->>'businessType',''),business_type),email=coalesce(nullif(p_profile->>'email',''),email),phone=coalesce(nullif(p_profile->>'phone',''),phone),county=coalesce(nullif(p_profile->>'county',''),county),town=coalesce(nullif(p_profile->>'town',''),town),address=coalesce(nullif(p_profile->>'address',''),address),latitude=coalesce((p_profile->>'latitude')::numeric,latitude),longitude=coalesce((p_profile->>'longitude')::numeric,longitude),service_radius_km=coalesce((p_profile->>'serviceRadiusKm')::numeric,service_radius_km),offers_mobile=coalesce((p_profile->>'offersMobile')::boolean,offers_mobile),has_workshop=coalesce((p_profile->>'hasWorkshop')::boolean,has_workshop),inspection_types=coalesce(p_profile->'inspectionTypes',inspection_types),service_terms=coalesce(p_profile->'serviceTerms',service_terms),status='pending',verification_status='unverified',lifecycle_stage='UNDER_REVIEW',updated_at=now(),lifecycle_updated_at=now() where public.inspection_providers.id=provider_id; return provider_id; end if;
insert into public.inspection_providers(user_id,company_name,trading_name,business_type,email,phone,county,town,address,latitude,longitude,service_radius_km,offers_mobile,has_workshop,inspection_types,service_terms,status,verification_status,lifecycle_stage) values(p_user_id,coalesce(nullif(p_profile->>'companyName',''),'Independent Inspector'),p_profile->>'tradingName',p_profile->>'businessType',p_profile->>'email',p_profile->>'phone',p_profile->>'county',p_profile->>'town',p_profile->>'address',(p_profile->>'latitude')::numeric,(p_profile->>'longitude')::numeric,coalesce((p_profile->>'serviceRadiusKm')::numeric,50),coalesce((p_profile->>'offersMobile')::boolean,true),coalesce((p_profile->>'hasWorkshop')::boolean,false),coalesce(p_profile->'inspectionTypes','[]'),coalesce(p_profile->'serviceTerms','{}'),'pending','unverified','UNDER_REVIEW') returning public.inspection_providers.id into provider_id; return provider_id; end; $$;
revoke all on function public.kayad_create_inspection_provider_application(uuid,jsonb) from public,anon,authenticated; grant execute on function public.kayad_create_inspection_provider_application(uuid,jsonb) to service_role;

-- Cross-domain review consistency: settlement uses closed bookings, therefore closed is reviewable when paid.
create or replace function public.kayad_submit_inspection_review_atomic(p_booking_id uuid,p_reviewer_id uuid,p_rating integer,p_comment text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare b public.inspection_bookings%rowtype;p public.inspection_providers%rowtype;rid uuid;
begin if p_rating not between 1 and 5 then raise exception 'Rating must be between 1 and 5'; end if; select * into b from public.inspection_bookings where id=p_booking_id for update; if not found or b.customer_id<>p_reviewer_id or b.status not in ('completed','closed','cancelled') or b.payment_status<>'fully_paid' then raise exception 'Only a completed paid inspection can be reviewed'; end if; select * into p from public.inspection_providers where id=b.provider_id; if not found then raise exception 'Provider not found'; end if; if exists(select 1 from public.inspection_reviews where booking_id=b.id and reviewer_id=p_reviewer_id) then raise exception 'Review already submitted'; end if; insert into public.inspection_reviews(provider_id,booking_id,reviewer_id,rating,comment,is_published,created_at,updated_at) values(p.id,b.id,p_reviewer_id,p_rating,nullif(trim(p_comment),''),true,now(),now()) returning id into rid; insert into public.inspection_provider_scorecards(provider_id,completed_inspections,completed_reviews,average_customer_rating,last_calculated_at,created_at,updated_at) values(p.id,1,1,p_rating,now(),now(),now()) on conflict(provider_id) do update set completed_reviews=public.inspection_provider_scorecards.completed_reviews+1,average_customer_rating=round(((public.inspection_provider_scorecards.average_customer_rating*public.inspection_provider_scorecards.completed_reviews)+p_rating)/(public.inspection_provider_scorecards.completed_reviews+1),2),last_calculated_at=now(),updated_at=now(); return jsonb_build_object('reviewId',rid,'providerId',p.id,'rating',p_rating); end; $$;
revoke all on function public.kayad_submit_inspection_review_atomic(uuid,uuid,integer,text) from public,anon,authenticated; grant execute on function public.kayad_submit_inspection_review_atomic(uuid,uuid,integer,text) to service_role;

-- Canonical settlement payout: 5100 provider payable -> 1000 platform cash. Previous live implementation incorrectly referenced 1200.
create or replace function public.kayad_mark_inspection_settlement_paid_atomic(p_settlement_id uuid,p_payment_method text,p_payment_reference text,p_user_id uuid default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare s public.inspection_settlements%rowtype;missing integer;cnt integer;
begin if nullif(trim(coalesce(p_payment_reference,'')),'') is null then raise exception 'Settlement payment reference is required'; end if; select * into s from public.inspection_settlements where id=p_settlement_id for update; if not found then raise exception 'Settlement not found'; end if; if s.status='paid' then if s.payment_reference=p_payment_reference then return jsonb_build_object('settlementId',s.id,'status','paid','idempotent',true,'paidAt',s.paid_at); end if; raise exception 'Settlement already paid with a different payment reference'; end if; if s.status<>'pending' then raise exception 'Settlement cannot be paid from %',s.status; end if; select count(*) into cnt from public.inspection_transactions where settlement_id=s.id and transaction_type='inspection_payment'; if cnt=0 then raise exception 'Settlement has no linked inspection payments'; end if; select count(*) into missing from public.inspection_transactions t left join public.inspection_bookings b on b.id=t.booking_id left join public.inspection_reports r on r.booking_id=t.booking_id where t.settlement_id=s.id and t.transaction_type='inspection_payment' and (b.id is null or b.status<>'closed' or b.payment_status<>'fully_paid' or r.id is null); if missing>0 then raise exception 'Settlement contains % inspection(s) that are not closed and reported',missing; end if; perform public.kayad_post_ledger_entry_atomic('inspection-payout:'||s.id::text,p_user_id,s.net_amount,coalesce(s.currency,'KES'),'inspection_payout','inspection_provider','Inspection provider payout',jsonb_build_object('settlement_id',s.id,'provider_id',s.provider_id),'5100','1000'); update public.inspection_settlements set status='paid',payment_method=p_payment_method,payment_reference=p_payment_reference,paid_at=now(),processed_at=now(),updated_at=now() where id=s.id; update public.inspection_transactions set status='completed' where settlement_id=s.id; insert into public.inspection_transactions(provider_id,settlement_id,transaction_type,amount,currency,status,description,reference,created_at) values(s.provider_id,s.id,'payout',s.net_amount,coalesce(s.currency,'KES'),'completed','Inspection provider payout',p_payment_reference,now()); return jsonb_build_object('settlementId',s.id,'status','paid','idempotent',false,'paidAt',now()); end; $$;
revoke all on function public.kayad_mark_inspection_settlement_paid_atomic(uuid,text,text,uuid) from public,anon,authenticated; grant execute on function public.kayad_mark_inspection_settlement_paid_atomic(uuid,text,text,uuid) to service_role;
